ALTER TABLE "ProjectLead"
  ALTER COLUMN "companyWebsite" DROP NOT NULL,
  ALTER COLUMN "companySize" DROP NOT NULL,
  ADD COLUMN "companyStage" TEXT,
  ADD COLUMN "teamSize" TEXT,
  ADD COLUMN "customerServiceArea" TEXT,
  ADD COLUMN "currentState" TEXT,
  ADD COLUMN "friction" TEXT,
  ADD COLUMN "importantTools" TEXT,
  ADD COLUMN "engagementShape" TEXT,
  ADD COLUMN "investmentContext" TEXT,
  ADD COLUMN "investmentNotes" TEXT,
  ADD COLUMN "preferredContactMethod" TEXT,
  ADD COLUMN "firstTouchSource" TEXT,
  ADD COLUMN "firstTouchMedium" TEXT,
  ADD COLUMN "firstTouchCampaign" TEXT,
  ADD COLUMN "lastTouchSource" TEXT,
  ADD COLUMN "lastTouchMedium" TEXT,
  ADD COLUMN "lastTouchCampaign" TEXT,
  ADD COLUMN "landingPage" TEXT,
  ADD COLUMN "referrer" TEXT,
  ADD COLUMN "qualificationSummary" TEXT,
  ADD COLUMN "nextAction" TEXT;
